-- =====================================================================
-- V1 — Baseline du schéma (état AVANT la réception partielle)
--
-- Ce fichier fige le schéma existant, généré jusqu'ici par
-- ddl-auto: update. Les bases déjà en place ne le rejoueront PAS
-- (baseline-on-migrate: true pose le marqueur flyway_schema_history
-- en V0) ; les bases neuves le créent à l'identique.
--
-- Généré depuis les entités JPA (Hibernate 6.4, PostgreSQL) :
--   * id : bigint GENERATED BY DEFAULT AS IDENTITY (AbstractEntity)
--   * createdAt/updatedAt : created_at / updated_at timestamp(6) NOT NULL
--   * BigDecimal : numeric(38,2)
--   * Instant : timestamp with time zone
--   * enums : varchar (EnumType.STRING)
-- Divergences connues (acceptées, sans effet à l'exécution) :
--   * les noms de contraintes FK/index sont lisibles ici (Hibernate
--     génère des noms hachés) ;
--   * article.photo : TEXT (certaines bases historiques l'ont en
--     varchar -- DataInitializer élargit la colonne au démarrage).
-- Prochaine évolution : V2 (réception partielle, §3.5).
-- =====================================================================

CREATE TABLE entreprise (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom varchar(255) NOT NULL,
    adresse1 varchar(255),
    adresse2 varchar(255),
    ville varchar(255),
    codepostal varchar(255),
    pays varchar(255),
    mail varchar(255),
    numtel varchar(255),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uc_entreprise_nom UNIQUE (nom)
);

CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uc_roles_nom UNIQUE (nom)
);

CREATE TABLE utilisateur (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom varchar(255) NOT NULL,
    prenom varchar(255) NOT NULL,
    login varchar(255) NOT NULL,
    motdepasse varchar(255) NOT NULL,
    mail varchar(255),
    numtel varchar(255),
    photo varchar(255),
    role varchar(255) NOT NULL,
    identreprise bigint,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uc_utilisateur_login UNIQUE (login)
);
ALTER TABLE utilisateur ADD CONSTRAINT FK_utilisateur_identreprise FOREIGN KEY (identreprise) REFERENCES entreprise;
CREATE INDEX IDX_utilisateur_identreprise ON utilisateur (identreprise);

CREATE TABLE categorie (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(255) NOT NULL,
    designation varchar(255) NOT NULL,
    identreprise bigint,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uc_categorie_code UNIQUE (code)
);
ALTER TABLE categorie ADD CONSTRAINT FK_categorie_identreprise FOREIGN KEY (identreprise) REFERENCES entreprise;
CREATE INDEX IDX_categorie_identreprise ON categorie (identreprise);

CREATE TABLE article (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codearticle varchar(255) NOT NULL,
    designation varchar(255) NOT NULL,
    prixunitaireht numeric(38,2) NOT NULL,
    tauxtva numeric(38,2) NOT NULL,
    prixunitairettc numeric(38,2) NOT NULL,
    photo text,
    stockactuel integer NOT NULL,
    seuilmin integer,
    idcategorie bigint,
    identreprise bigint,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uc_article_codearticle UNIQUE (codearticle)
);
ALTER TABLE article ADD CONSTRAINT FK_article_idcategorie FOREIGN KEY (idcategorie) REFERENCES categorie;
ALTER TABLE article ADD CONSTRAINT FK_article_identreprise FOREIGN KEY (identreprise) REFERENCES entreprise;
CREATE INDEX IDX_article_idcategorie ON article (idcategorie);
CREATE INDEX IDX_article_identreprise ON article (identreprise);

CREATE TABLE client (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom varchar(255) NOT NULL,
    prenom varchar(255) NOT NULL,
    adresse1 varchar(255),
    adresse2 varchar(255),
    ville varchar(255),
    codepostal varchar(255),
    pays varchar(255),
    photo varchar(255),
    mail varchar(255),
    numtel varchar(255),
    identreprise bigint,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);
ALTER TABLE client ADD CONSTRAINT FK_client_identreprise FOREIGN KEY (identreprise) REFERENCES entreprise;
CREATE INDEX IDX_client_identreprise ON client (identreprise);

CREATE TABLE fournisseur (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom varchar(255) NOT NULL,
    adresse1 varchar(255),
    adresse2 varchar(255),
    ville varchar(255),
    codepostal varchar(255),
    pays varchar(255),
    mail varchar(255),
    numtel varchar(255),
    identreprise bigint,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);
ALTER TABLE fournisseur ADD CONSTRAINT FK_fournisseur_identreprise FOREIGN KEY (identreprise) REFERENCES entreprise;
CREATE INDEX IDX_fournisseur_identreprise ON fournisseur (identreprise);

CREATE TABLE commandeclient (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(255) NOT NULL,
    datecommande timestamp with time zone NOT NULL,
    statut varchar(255) NOT NULL,
    idclient bigint,
    identreprise bigint,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uc_commandeclient_code UNIQUE (code)
);
ALTER TABLE commandeclient ADD CONSTRAINT FK_commandeclient_idclient FOREIGN KEY (idclient) REFERENCES client;
ALTER TABLE commandeclient ADD CONSTRAINT FK_commandeclient_identreprise FOREIGN KEY (identreprise) REFERENCES entreprise;
CREATE INDEX IDX_commandeclient_idclient ON commandeclient (idclient);
CREATE INDEX IDX_commandeclient_identreprise ON commandeclient (identreprise);

CREATE TABLE lignecommandeclient (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantite integer NOT NULL,
    prixunitaire numeric(38,2) NOT NULL,
    idarticle bigint NOT NULL,
    idcommandeclient bigint,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);
ALTER TABLE lignecommandeclient ADD CONSTRAINT FK_lignecommandeclient_idarticle FOREIGN KEY (idarticle) REFERENCES article;
ALTER TABLE lignecommandeclient ADD CONSTRAINT FK_lignecommandeclient_idcommandeclient FOREIGN KEY (idcommandeclient) REFERENCES commandeclient;
CREATE INDEX IDX_lignecommandeclient_idarticle ON lignecommandeclient (idarticle);
CREATE INDEX IDX_lignecommandeclient_idcommandeclient ON lignecommandeclient (idcommandeclient);

CREATE TABLE commandefournisseur (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(255) NOT NULL,
    datecommande timestamp with time zone NOT NULL,
    statut varchar(255) NOT NULL,
    idfournisseur bigint,
    identreprise bigint,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uc_commandefournisseur_code UNIQUE (code)
);
ALTER TABLE commandefournisseur ADD CONSTRAINT FK_commandefournisseur_idfournisseur FOREIGN KEY (idfournisseur) REFERENCES fournisseur;
ALTER TABLE commandefournisseur ADD CONSTRAINT FK_commandefournisseur_identreprise FOREIGN KEY (identreprise) REFERENCES entreprise;
CREATE INDEX IDX_commandefournisseur_idfournisseur ON commandefournisseur (idfournisseur);
CREATE INDEX IDX_commandefournisseur_identreprise ON commandefournisseur (identreprise);

CREATE TABLE lignecommandefournisseur (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantite integer NOT NULL,
    prixunitaire numeric(38,2) NOT NULL,
    idarticle bigint NOT NULL,
    idcommandefournisseur bigint,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);
ALTER TABLE lignecommandefournisseur ADD CONSTRAINT FK_lignecommandefournisseur_idarticle FOREIGN KEY (idarticle) REFERENCES article;
ALTER TABLE lignecommandefournisseur ADD CONSTRAINT FK_lignecommandefournisseur_idcommandefournisseur FOREIGN KEY (idcommandefournisseur) REFERENCES commandefournisseur;
CREATE INDEX IDX_lignecommandefournisseur_idarticle ON lignecommandefournisseur (idarticle);
CREATE INDEX IDX_lignecommandefournisseur_idcommandefournisseur ON lignecommandefournisseur (idcommandefournisseur);

CREATE TABLE vente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(255) NOT NULL,
    datevente timestamp with time zone NOT NULL,
    idclient bigint,
    identreprise bigint,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uc_vente_code UNIQUE (code)
);
ALTER TABLE vente ADD CONSTRAINT FK_vente_idclient FOREIGN KEY (idclient) REFERENCES client;
ALTER TABLE vente ADD CONSTRAINT FK_vente_identreprise FOREIGN KEY (identreprise) REFERENCES entreprise;
CREATE INDEX IDX_vente_idclient ON vente (idclient);
CREATE INDEX IDX_vente_identreprise ON vente (identreprise);

CREATE TABLE lignevente (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantite integer NOT NULL,
    prixunitaire numeric(38,2) NOT NULL,
    idarticle bigint NOT NULL,
    idvente bigint,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);
ALTER TABLE lignevente ADD CONSTRAINT FK_lignevente_idarticle FOREIGN KEY (idarticle) REFERENCES article;
ALTER TABLE lignevente ADD CONSTRAINT FK_lignevente_idvente FOREIGN KEY (idvente) REFERENCES vente;
CREATE INDEX IDX_lignevente_idarticle ON lignevente (idarticle);
CREATE INDEX IDX_lignevente_idvente ON lignevente (idvente);

CREATE TABLE mvtstk (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar(255) NOT NULL,
    quantite integer NOT NULL,
    datemouvement timestamp with time zone NOT NULL,
    motif varchar(255),
    stockapresmouvement integer NOT NULL,
    origine varchar(255),
    idarticle bigint NOT NULL,
    identreprise bigint NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);
ALTER TABLE mvtstk ADD CONSTRAINT FK_mvtstk_idarticle FOREIGN KEY (idarticle) REFERENCES article;
ALTER TABLE mvtstk ADD CONSTRAINT FK_mvtstk_identreprise FOREIGN KEY (identreprise) REFERENCES entreprise;
CREATE INDEX IDX_mvtstk_idarticle ON mvtstk (idarticle);
CREATE INDEX IDX_mvtstk_identreprise ON mvtstk (identreprise);
