-- =====================================================================
-- V5 — Refresh tokens (§6.3 du cahier des charges)
--
-- Un refresh token opaque par utilisateur (l'émission d'un nouveau
-- révoque les précédents : rotation). Le token n'est JAMAIS stocké en
-- clair : seul son hash SHA-256 l'est, pour qu'un vol de la base ne
-- permette pas de forger des sessions.
--
-- Pas de contrainte CHECK ni d'enum : une table technique simple.
-- La purge des tokens expirés est faite par un job Spring quotidien,
-- pas par la base.
-- =====================================================================

CREATE TABLE refreshtoken (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tokenhash varchar(64) NOT NULL,
    idutilisateur bigint NOT NULL,
    expireat timestamp with time zone NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uc_refreshtoken_tokenhash UNIQUE (tokenhash),
    CONSTRAINT fk_refreshtoken_utilisateur FOREIGN KEY (idutilisateur)
        REFERENCES utilisateur (id)
);

CREATE INDEX idx_refreshtoken_utilisateur ON refreshtoken (idutilisateur);
CREATE INDEX idx_refreshtoken_expireat ON refreshtoken (expireat);
